relativeURLs = true
title = "Lirong Yang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = ""
    logo = "Yang_headshot1.jpg" 
    
