relativeURLs = true
title = "hellow"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "test"
    logo = "Rao_headshot_berkeley.jpg" 
    
